package Prototype.StateArchitecture.State;

import Prototype.SpecificationParser.RenameTransformation;
import Prototype.SpecificationParser.ReplaceTransformation;
import Prototype.SpecificationParser.TransformationFormat;
import Prototype.StateArchitecture.Transducer.Transducer;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

import java.io.IOException;

import static Prototype.Utils.Helper.writeJsonValue;

public class Match implements State {
    private final Transducer transducer;    
    private final TransformationFormat specification;

    public Match(Transducer transducer) {
        this.transducer = transducer;        
        this.specification = transducer.getSpecification();
    }

    @Override
    public void process(JsonParser parser) {        
        JsonToken event = parser.currentToken();
        JsonGenerator generator = transducer.getGenerator();
        // parser is positioned at a match - either a fieldname or a value
        switch (transducer.getTransformationType()) {
            case "rename":
                // current token MUST be a fieldname
                try {
                    generator.writeFieldName(((RenameTransformation) specification).getKey());
                    transducer.setState(transducer.getGenState());
                    // induces move to the next token, current fieldname is skipped 
                    transducer.setPaused(false);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
                break;
            case "remove":
                // current token is either a fieldname or a value
                transducer.setState(transducer.getSkipSubtreeState());
                // we want skipsubtree state to process also the current token
                // (the skipsubtree state handles also movement from a fieldname to a value if necessary)
                transducer.setPaused(true);
                break;
            case "replace":
                // current token is either a fielddame or a value
                try {
                    // replaces current fieldname if specified - current token must be a fieldname
                    // TODO report error for arrays
                    if (((ReplaceTransformation) specification).getKey() != null) {
                        generator.writeFieldName(((ReplaceTransformation) specification).getKey());
                    // current key is copied only in case of object field name, it doesn't make sense for other cases
                    } else if (transducer.getPaStack().peek() >= 0 && event == JsonToken.FIELD_NAME) {
                        generator.copyCurrentEvent(parser);
                    }

                    writeJsonValue(generator, ((ReplaceTransformation) specification).getValue());
                    // we want skipsubtree state to process also the current token
                    // (the skipsubtree state handles also movement from a fieldname to a value if necessary)
                    transducer.setState(transducer.getSkipSubtreeState());
                    transducer.setPaused(true);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
                break;
            // add and copy yield the same code
            case "add":
                /*// current token is either a fieldname or a value                
                    transducer.setState(transducer.getFindPosState());                                        
                    // current event is generated by entered FindPos state
                    //generator.copyCurrentEvent(parser);                                            
                    transducer.setPaused(false);                
                break;*/            
            case "copy": 
                transducer.setState(transducer.getFindPosState());                
                transducer.setPaused(false);
                break;
            default:
                break;
        }
    }

    @Override
    public boolean isGenerating() {
        return false;
    }
}
